name: fripesfinderv2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  google_maps_flutter: ^2.5.0
  image_picker: ^1.0.4
  firebase_core: ^2.24.0
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.6.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  go_router: ^13.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/autumn_flower.png
    - lib/assets/black_corset.PNG
    - lib/assets/black_yellows_diamonds.PNG
    - lib/assets/blue_ceramic.PNG
    - lib/assets/blue_strips.PNG
    - lib/assets/blue_tartan.PNG
    - lib/assets/crimson_petals.PNG
    - lib/assets/cute_birds.PNG
    - lib/assets/feline_spot.PNG
    - lib/assets/green_tiles.PNG
    - lib/assets/pink_blue_flowers.PNG
    - lib/assets/pink_lace.PNG
    - lib/assets/shining_dress.PNG
    - lib/assets/starlit_jeans.PNG
    - lib/assets/sunrise.PNG
    - lib/assets/zebra.PNG
